name 'korben'
maintainer 'Tyler Fitch'
maintainer_email 'chef@tylerfitch.com'
license 'MIT'
description 'Wrapper cookbook that configures Korben'
long_description 'Wrapper cookbook that configures Korben'
version '0.2.0'

depends 'makemkv'
depends 'plexapp'
